# Generated by Django 4.2.11 on 2024-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_page",
            field=models.BooleanField(default=False, verbose_name="Is a page?"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=450, verbose_name="Short description"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Post Title"),
        ),
    ]
