# Generated by Django 4.2.6 on 2024-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/shelters/gallery/",
                verbose_name="Principal Image",
            ),
        ),
    ]
