# Generated by Django 4.2.13 on 2024-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0002_alter_shelter_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
