# Generated by Django 4.2.6 on 2023-10-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adopter", "0001_initial"),
        ("pet", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("special_condition", "Special Condition"),
                            ("reserved", "Reserved"),
                            ("waiting", "Waiting"),
                            ("adopted", "Adopted"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                        verbose_name="Adoption Status",
                    ),
                ),
                (
                    "extra_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Extra Location",
                    ),
                ),
                ("entry_date", models.DateTimeField(verbose_name="Entry Date")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "history",
                    models.TextField(blank=True, null=True, verbose_name="History"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adoption",
                "verbose_name_plural": "Adoptions",
            },
        ),
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Request Status",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message to Shelter"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Response from Shelter"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adopter.adopter",
                        verbose_name="Adopter",
                    ),
                ),
                (
                    "adoption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adoption.adoption",
                        verbose_name="Adoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adoption Request",
                "verbose_name_plural": "Adoption Requests",
            },
        ),
    ]
