# Generated by Django 4.2.6 on 2023-10-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shelter", "0001_initial"),
        ("adopter", "0001_initial"),
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("special_condition", "Special Condition"),
                            ("reserved", "Reserved"),
                            ("waiting", "Waiting"),
                            ("adopted", "Adopted"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=20,
                        verbose_name="Adoption Status",
                    ),
                ),
                (
                    "extra_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Extra Location",
                    ),
                ),
                ("entry_date", models.DateTimeField(verbose_name="Entry Date")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "adopted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoptions_received",
                        to="adopter.adopter",
                        verbose_name="Adopted By",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelter.shelter",
                        verbose_name="Shelter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoptions_made",
                        to="adopter.adopter",
                        verbose_name="Adopter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adoption",
                "verbose_name_plural": "Adoptions",
            },
        ),
    ]
