# Generated by Django 4.2.13 on 2024-05-28 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adoption", "0002_adoptionapplication_option_question_questionnaire_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Adoption",
        ),
    ]
