# Generated by Django 4.2.6 on 2024-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petimage",
            name="pet",
        ),
        migrations.AddField(
            model_name="pet",
            name="images",
            field=models.ManyToManyField(to="pet.petimage"),
        ),
        migrations.AddField(
            model_name="pet",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="characteristics",
            field=models.ManyToManyField(
                related_name="pets",
                to="pet.characteristic",
                verbose_name="List of Characteristics",
            ),
        ),
        migrations.AlterField(
            model_name="petimage",
            name="image",
            field=models.ImageField(upload_to="static/pets/gallery/"),
        ),
    ]
