# Generated by Django 4.2.13 on 2024-05-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0002_remove_petimage_pet_pet_images_pet_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petimage",
            name="image",
            field=models.ImageField(upload_to="pets/gallery/"),
        ),
    ]
