# Generated by Django 4.2.13 on 2024-06-07 21:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_alter_petimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[380, 380],
                upload_to="pets/gallery/",
            ),
        ),
    ]
