# Generated by Django 4.2.6 on 2023-10-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
        ("adopter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adopter",
            name="preferred_pet_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pet.size",
            ),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="preferred_species",
            field=models.ManyToManyField(
                blank=True, null=True, to="pet.specie", verbose_name="Preferred Species"
            ),
        ),
    ]
