# Generated by Django 4.2.13 on 2024-05-28 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adopter", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdopterPreferences",
        ),
    ]
