# Generated by Django 4.2.6 on 2023-10-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adopter", "0002_alter_adopter_preferred_pet_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adopter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
